### ISSUE TITLE
Samurai documentation optimisation suggestions

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/docs#137]
PlatON Samurai issue：
https://devdocs.platon.network/docs/en/Samurai_user_manual/
1，Samurai operating manual missing English documentation
![image](https://user-images.githubusercontent.com/29141931/132840303-a0a30728-1386-45a7-99ad-07f3f748f09f.png)

2，The images in the documentation do not correspond to Platon
![image](https://user-images.githubusercontent.com/29141931/132840345-123db6c7-a429-4ae2-9ebf-91d3819adb85.png)

3，Suggested formatting for the document title

**Comment by biganxin** [comment]
@xiyu1984 @fksyuan

**Comment by biganxin** [comment]
Samurai中文文档 图片没有对应LAT网络，另外格式标点等不规范

**Comment by biganxin** [comment]
@Acsill will fix it

**Comment by wetezos** [comment]
We will fix it.
