### ISSUE TITLE
JS SDK 英文文档翻译

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/Docs#151]
【翻译需求】
参照下述Commit的中文修改内容，修改对应JS SDK英文文档
https://github.com/PlatONnetwork/docs/commit/e59ad2417735e4c3ddfd525c23cfbf5f3538400e

**Comment by biganxin** [comment]
@WillXing has claimed this task

**Comment by WillXing** [comment]
@biganxin ， 对应英文文档的位置在哪里？

**Comment by WillXing** [comment]
👉 https://github.com/PlatONnetwork/docs/pull/152
