### ISSUE TITLE
【Bounty】Dapp integration with Walletconnect development guide for connecting to ATON wallets and signing transactions

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/Docs#171]
The Walletconnect protocol is now supported by ATON.

Junior community developers are being guided through the integration of the Dapp (web) Walletconnect protocol and the implementation of a connection to the ATON wallet and the authorisation of transactions to be signed.

We are now looking for community developers to integrate and test mobile signatures based on the relevant Dapp Demo and output a detailed development guide (in the form of a document or video).

Walletconnect short description document: https://devdocs.platon.network/docs/zh-CN/walletconnect_tutorial

DM Telegram:  https://t.me/Boneybi ，Discord：https://discord.gg/GTbFshp9sw

**Comment by liuzhengbo** [comment]
报名，计划完成时间 2021-12-15之前，lat地址：lat1xxsz8u3z0hdvruf5ndtun3rz38m55x8ezq2q4s

[DApp Connect With ATON By WalletConnect.md](https://github.com/PlatONnetwork/docs/files/7768995/DApp.Connect.With.ATON.By.WalletConnect.md)

**Comment by JinJinxx** [comment]
报名，计划完成时间2021-12-30号，联系邮箱：Jin@digquant.tech  lat地址：lat1x2mgyd9qeewcs906lmdznfywdpxqvqp8spg3rm
[https://forum.latticex.foundation/t/topic/5940](url)

**Comment by biganxin** [comment]
Thank you for @JinJinxx @liuzhengbo  support, the reward has been applied and is expected to be paid within 7 working days
For queries, please contact Discord (Boney_bee#915)
