### ISSUE TITLE
【Bounty】Best practice tutorial - MetaMask with PlatON SDK to build, sign and send WASM transactions

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/Docs#181]
## Overview
A best practice tutorial on building transactions using PlatON's SDK, signing them with the MetaMask wallet and sending WASM transactions via PlatON's SDK. 
Requirements: clear and complete content for beginners, with the possibility of recording video tutorials.

## Sign up
This issue replies to.
Sign up + delivery time + address to receive the reward + contact details

## Reward
1800LAT

Any questions please contact：
Telegram: https://t.me/Boneybi , Discord: https://discord.gg/GTbFshp9sw

**Comment by hthuang996** [comment]
[sign up]
delivery time:2021/12/31
delivery form:demo on github, document tutorial
address to receive the reward:lat14amuzj9n6cgwxs247aas4nmglxfkyvj6kwwzns
contact:https://t.me/hthuang996

**Comment by biganxin** [comment]
Thank you for your support and we look forward to your delivery

**Comment by hthuang996** [comment]
Demo: https://github.com/hthuang996/platon-wasm-metamask-demo
Tutorial: https://github.com/hthuang996/platon-wasm-metamask-demo#readme

**Comment by hthuang996** [comment]
In case of any question, please contact me.

**Comment by biganxin** [comment]
@hthuang996  It's very efficient, so please post this tutorial (which may need to be properly optimised) to the forum and documentation library

**Comment by biganxin** [comment]
Thank you for your support, the reward has been applied and is expected to be paid within 7 working days
For queries, please contact Discord (Boney_bee#0915)
