### ISSUE TITLE
How to participate current test network

### ISSUE THREAD

**Issue by xiaogan18** [PlatONnetwork/docs#3]
I follow with document 'to be a node',it seems doesn't completed.when I run below command :
```shell 
mkdir -p ~/platon-node/data && keytool genkeypair | tee >(grep "PrivateKey" | awk '{print $2}' > ./data/nodekey) >(grep "PublicKey" | awk '{print $3}' > ./data/nodeid)
```
I got this
```shell 
Illegal option:  genkeypair
Key and Certificate Management Tool
```
Can you help me to deploy a node participate current test network ?

**Comment by jerk188** [comment]
Hello, your problem may be in conflict with Java's keytool tool. How did you install the platon node? PPA or source code compilation? If you are installing PPA, you can check whether the installed version is version 0.12.1 through the command, command: platon version. If the source code is compiled, is there a copy of the latest 0.12.1 executable file keytool to your platon-node directory, execute the command in the platon-node directory: mkdir -p ~/platon-node/data &&. /keytool genkeypair | tee >(grep "PrivateKey" | awk'{print $2}'> ./data/nodekey) >(grep "PublicKey" | awk'{print $3}'> ./data/nodeid)

**Comment by xiaogan18** [comment]
by PPA ,install failed
``` shell
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package platon0.12.1
E: Couldn't find any package by glob 'platon0.12.1'
E: Couldn't find any package by regex 'platon0.12.1'
```

**Comment by jerk188** [comment]
Are you a ubuntu18.04 system? If it is ubuntu18.04, is there a PPA source added? If there is a PPA source added, has it been updated?

  #Add PPA source and update
  $ sudo add-apt-repository ppa:ppatwo/platon
  $ sudo apt-get update
  #View the platon version that can be installed
  $ sudo apt search platon
  # Install platon0.12.1
  $ sudo apt install -y platon0.12.1

**Comment by xiaogan18** [comment]
No, actually I'm 16.04.And I added the PPA source also updated.

**Comment by jerk188** [comment]
Sorry, the current PPA package is only compatible with ubuntu18.04 system, please update to ubuntu18.04 if conditions permit.

**Comment by xiaogan18** [comment]
So if conditions not permitted, is there any other way ?

**Comment by jerk188** [comment]
Sorry, because our PlatON is based on ubuntu18.04, all verifications are completed. If you use other versions of the system, there is no guarantee that other problems will occur.

**Comment by xiaogan18** [comment]
OK, thanks
