### ISSUE TITLE
PlatON CLI Doc

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/docs#74]
![image](https://user-images.githubusercontent.com/29141931/123386025-c928c580-d5c8-11eb-9e85-9d8c0ab7e804.png)
Suggested changes to the text in the picture

**Comment by biganxin** [comment]
help wanted
https://devdocs.platon.network/docs/zh-CN/Command_Line_Tools/
https://devdocs.platon.network/docs/en/Command_Line_Tools/
![image](https://user-images.githubusercontent.com/29141931/131437758-fdf5455a-9088-4d4b-a443-50470e86fe9d.png)

**Comment by biganxin** [comment]
@Acsill

**Comment by kaf-lamed-beyt** [comment]
Hi @biganxin,

How do I go about fixing this?

**Comment by biganxin** [comment]
> Hi @biganxin,
> 
> How do I go about fixing this?
You are not very familiar with PlatON's underlying layer, this may not be suitable for you to modify oh

**Comment by biganxin** [comment]
@cheng762 @jiangshangqifeng 
Many of the commands in this document are still ethereum commands or very old versions of commands, so it is recommended to review and modify them.
See Alaya Doc seems to have basically changed, in addition may need to increase the platonkey instructions.
![image](https://user-images.githubusercontent.com/29141931/138382524-cc20228f-8023-451f-a9e0-daf36e61b715.png)

![image](https://user-images.githubusercontent.com/29141931/138382459-118480b1-7f75-4aa3-b751-afd81b3365c9.png)

**Comment by benbaley** [comment]
@cheng762 these docs are somewhat out of date, please update them :)

**Comment by benbaley** [comment]
@biganxin PTAL https://github.com/PlatONnetwork/docs/pull/153/commits/281f13143783b67ae4f564a3a45f5df8a330df57
