### ISSUE TITLE
JS SDK文案问题

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/docs#76]
JS SDK有15处关于以太坊文案待修改项
https://devdocs.platon.network/docs/zh-CN/JS_SDK/

**Comment by biganxin** [comment]
@luo-dahui

**Comment by biganxin** [comment]
https://devdocs.platon.network/docs/zh-CN/JS_SDK/
https://devdocs.platon.network/docs/en/JS_SDK/
Search ether
Search for 以太坊

**Comment by biganxin** [comment]
@Caleb335 This is a very simple task, maybe you can come and do it.
Methods: 
1, Chinese document: https://devdocs.platon.network/docs/zh-CN/JS_SDK/
Search for "以太坊" in the documentation and replace "以太坊" with "PlatON"

Alaya document the same problem, you can also help to modify:  https://github.com/AlayaNetwork/alaya-devdocs/issues/103

**Comment by kaf-lamed-beyt** [comment]
Alright @biganxin 

Kindly assign me
